server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /recommend {
        proxy_pass http://backend:5000;
    }

    location /save_routine {
        proxy_pass http://backend:5000;
    }

    location /weekly_stats {
        proxy_pass http://backend:5000;
    }

    location /get_routines {
        proxy_pass http://backend:5000;
    }
}